services:
  wiremock:
    container_name: users
    image: wiremock/wiremock:latest
    ports:
      - "8000:8080"
    volumes:
      - ./files/:/home/wiremock/__files/
      - ./mappings/:/home/wiremock/mappings
